api_platform:
    title: Hello API Platform
    version: 1.0.0

    show_webby: false

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
        html: [ 'text/html' ]
        multipart: [ 'multipart/form-data' ]

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
        pagination_client_enabled: false
        pagination_client_items_per_page: false
        pagination_client_partial: false
        pagination_enabled: true
        pagination_items_per_page: 10


    resource_class_directories:
        - '%kernel.project_dir%/src/ValueObject'
