vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        kbis:
            uri_prefix: /upload/kbis
            upload_destination: '%kernel.project_dir%/public/upload/kbis'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
