name: Deployment Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      working-directory: ./backend

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --ignore-platform-reqs

    - name: Run test suite
      run: composer run-script test

    - if: failure()
      uses: Ilshidur/action-discord@0.3.2
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: BOT ChallengeS3
        DISCORD_AVATAR: https://resize.programme-television.ladmedia.fr/r/670,670/img/var/premiere/storage/images/tele-7-jours/news-tv/oss-117-le-caire-nid-d-espions-c8-le-show-de-jean-dujardin-4484285/90175763-1-fre-FR/OSS-117-Le-Caire-nid-d-espions-C8-Le-show-de-Jean-Dujardin.jpg
      with:
        args: 'Tests before deployment of the Backend failed!'

  deploy:
    runs-on: self-hosted

    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update src folder
        run: |
          rm -rf ~/lab/prod_back/src/*
          cp -r backend/src/* ~/lab/prod_back/src

      - name: Update public folder
        run: |
          sudo rm -rf ~/lab/prod_back/public/*
          cp -r backend/public/* ~/lab/prod_back/public

      - name: Update config folder
        run: |
          sudo rm -rf ~/lab/prod_back/config/*
          cp -r backend/config/* ~/lab/prod_back/config

      - name: Update migrations folder
        run: |
          mkdir -p ~/lab/prod_back/migrations
          sudo rm -rf ~/lab/prod_back/migrations/*

      - name: Update .env file
        run: |
          rm -rf ~/lab/prod_back/.env
          cp -r backend/.env ~/lab/prod_back/.env
          cp -r ~/lab/.env.back ~/lab/prod_back/.env.local

      - name: Update composer.json file
        run: |
          rm -rf ~/lab/prod_back/composer.json
          cp -r backend/composer.json ~/lab/prod_back/composer.json

      - name: Update composer.lock file
        run: |
          rm -rf ~/lab/prod_back/composer.lock
          cp -r backend/composer.lock ~/lab/prod_back/composer.lock

      - name: Update dependencies
        run: |
          cd ~/lab/prod_back
          docker compose exec php composer install

      - name: Update certificates
        run: |
          cd ~/lab/prod_back
          docker compose exec php php bin/console lexik:jwt:generate-keypair -n --overwrite

      # - name: Migrations
      #   run: |
      #     cd ~/lab/prod_back
      #     docker compose exec php rm -r migrations
      #     docker compose exec php mkdir migrations
      #     docker compose exec php php bin/console make:migration -n
      #     docker compose exec php php bin/console d:m:m -n
      #     docker compose exec php php bin/console d:f:l -n

      - if: ${{failure() || success()}}
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: BOT ChallengeS3
          DISCORD_AVATAR: https://resize.programme-television.ladmedia.fr/r/670,670/img/var/premiere/storage/images/tele-7-jours/news-tv/oss-117-le-caire-nid-d-espions-c8-le-show-de-jean-dujardin-4484285/90175763-1-fre-FR/OSS-117-Le-Caire-nid-d-espions-C8-Le-show-de-Jean-Dujardin.jpg
        with:
          args: ${{ job.status == 'success' && 'Success ! The backend has been deployed.' || 'Error ! The backend has been not deployed.' }}