name: Test with PHPUnit

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      working-directory: ./backend

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --ignore-platform-reqs

    - name: Run test suite
      run: composer run-script test
  
  notification:
    runs-on: ubuntu-latest

    needs: build-test
    if: |
      always() && (needs.build-test.result == 'success' || needs.build-test.result == 'skipped')

    steps:
      - name: Discord notification
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: BOT ChallengeS3
          DISCORD_AVATAR: https://resize.programme-television.ladmedia.fr/r/670,670/img/var/premiere/storage/images/tele-7-jours/news-tv/oss-117-le-caire-nid-d-espions-c8-le-show-de-jean-dujardin-4484285/90175763-1-fre-FR/OSS-117-Le-Caire-nid-d-espions-C8-Le-show-de-Jean-Dujardin.jpg
        with:
          args: ${{ job.status == 'success' && 'Tests Backend passed!' || 'Tests Backend failed!' }}