name: CI PHPUnit

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      working-directory: ./backend

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --ignore-platform-reqs

    - name: Run test suite
      run: composer run-script test
  
  notification:
    runs-on: ubuntu-latest

    needs: build-test
    if: |
      always() && (needs.build-test.result == 'success' || needs.build-test.result == 'skipped')

    steps:
      - name: Discord notification
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: ${{ job.status == 'success' && 'Tests passed!' || 'Tests failed!' }}

          

    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_CHANNEL: alert
          SLACK_COLOR: "${{ job.status == 'success' && 'good' || 'danger' }}"