name: Deploy to Debian Server

on:
  push:
    branches:
      - feature/ci-cd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Git pull on server
      run: |
        ssh -i ~/.ssh/id_rsa debian@5.196.23.210 "cd ~/lab/challengeS3"
# ssh -i ~/.ssh/id_rsa debian@5.196.23.210 "cd ~/lab/challengeS3 && git pull"

    - name: npm install and build frontend
      run: |
        ssh -i ~/.ssh/id_rsa debian@5.196.23.210 "cd ~/lab/challengeS3/frontend && npm install && npm run build"

    - name: Copy build to /var/www/html
      run: |
        ssh -i ~/.ssh/id_rsa debian@5.196.23.210 "sudo cp -r ~/lab/challengeS3/frontend/build /var/www/html"

    - name: Composer install in backend
      run: |
        ssh -i ~/.ssh/id_rsa debian@5.196.23.210 "docker-compose exec php php composer install" 

    - name: Doctrine migrations in backend
      run: |
        ssh -i ~/.ssh/id_rsa debian@5.196.23.210 "docker-compose exec php php bin/console doctrine:migrations:migrate -n"

    - name: Doctrine fixtures in backend
      run: |
        ssh -i ~/.ssh/id_rsa debian@5.196.23.210 "docker-compose exec php php bin/console doctrine:fixtures:load -n"

    - name: Clear cache in backend
      run: |
        ssh -i ~/.ssh/id_rsa debian@5.196.23.210 "docker-compose exec php php bin/console cache:clear"