name: Deployment

on:
  push:
    branches:
      - main
      - dev
      - feature/deploy-app

  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: self-hosted

    env:
      working-directory: ./frontend

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

  deploy:
    runs-on: self-hosted

    needs: build
    if: |
      always() && (needs.build.result == 'success' || needs.build.result == 'skipped')

    steps:
      - name: Deploy
        run: echo "Deploying to production"
