name: Deployment

on:
  push:
    branches:
      - main
      - dev
      - feature/deploy-app

  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: self-hosted

    env:
      working-directory: ./frontend

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present
  
  notification:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Discord notification
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ChallengeS3 BOT
          DISCORD_AVATAR: https://resize.programme-television.ladmedia.fr/r/670,670/img/var/premiere/storage/images/tele-7-jours/news-tv/oss-117-le-caire-nid-d-espions-c8-le-show-de-jean-dujardin-4484285/90175763-1-fre-FR/OSS-117-Le-Caire-nid-d-espions-C8-Le-show-de-Jean-Dujardin.jpg
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'