name: Test with cypress

on:
  push:
    branches:
      - main
      - dev
      - feature/test-cypress-front

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      working-directory: ./frontend

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm i -D cypress
          working-directory: ${{ env.working-directory }}
    

    
  
  # notification:
  #   runs-on: ubuntu-latest

  #   needs: build-test
  #   if: |
  #     always() && (needs.build-test.result == 'success' || needs.build-test.result == 'skipped')

  #   steps:
  #     - name: Discord notification
  #       uses: Ilshidur/action-discord@0.3.2
  #       env:
  #         DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  #       with:
  #         args: ${{ job.status == 'success' && 'Tests passed!' || 'Tests failed!' }}