name: Test with cypress

on:
  push:
    branches:
      - main
      - dev
      - feature/test-cypress-front

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      working-directory: ./frontend

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run dev
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 60
          wait-on-timeout-error: 'Timed out waiting for the application to start'
          wait-on-retry-interval: 5000
          wait-on-silent: false
          record: true
          parallel: true
          group: 'Cypress Tests'
          spec: cypress/e2e/**/*.cy.js
          browser: chrome
          headless: true
          config-file: cypress.json
    

    
  
  # notification:
  #   runs-on: ubuntu-latest

  #   needs: build-test
  #   if: |
  #     always() && (needs.build-test.result == 'success' || needs.build-test.result == 'skipped')

  #   steps:
  #     - name: Discord notification
  #       uses: Ilshidur/action-discord@0.3.2
  #       env:
  #         DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  #       with:
  #         args: ${{ job.status == 'success' && 'Tests passed!' || 'Tests failed!' }}