name: React JS

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'frontend/**'
      - '.github/workflows/**'

  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'frontend/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      working-directory: ./frontend

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - uses: actions/checkout@v3

      - name: Install node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install NPM Dependencies
        run: npm i

      - name: Build Project
        run: npm run build

      - name: Test with curl
        run: |
          npm run preview &
          sleep 5
          curl -v http://localhost:4173/ -I

  notification:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Discord notification
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: 'The build is done!'

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Install node 20
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 20.x

  #     - name: Install NPM Dependencies
  #       run: npm i

  #     - name: Build Project
  #       run: npm run build

  #     - uses: actions/cache@v3
  #       name: Setup npm cache
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-node-

      # - name: Install Vercel CLI
      #   run: pnpm install --global vercel@latest

      # - name: Pull Vercel Environment Information
      #   run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # - name: Build Project Artifacts
      #   run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      # - name: Deploy Project Artifacts to Vercel
      #   run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
